### ISSUE TITLE
Artifact sizes and bootstrap in Cloud native environments.

### ISSUE THREAD

**Issue by debrutal** [security-union/rust-vs-java#2]
One huge aspect we face in a project is, that Java does perform pretty bad on highly dynamic infrastructure, as it's startup time is "horrible" for an interpreted language.

Using services like google cloud run or cloud functions with dynamic scaling down to zero have highly impact on first requests per instance.

Especially when using JVM in default configuration with frameworks like Spring/Graal/Micronaut, as they often have some beans which are initialized lazily at first invocation.

**Comment by darioalessandro** [comment]
makes sense :( probably that is why they added rust support: no initialization penalty.

How do cloud functions perform in Go?

**Comment by debrutal** [comment]
I have little experience on golang and no experience in running golang based application at all nor in cloud functions.
I can imagine it should be at a similar class of rust, being natively compiled.
 
Rust is not supported in Cloud Functions, you gotta go for the Cloud Run solution and containerize your artifact.

**Comment by darioalessandro** [comment]
AWS Lambdas in Rust!! https://docs.aws.amazon.com/sdk-for-rust/latest/dg/lambda.html
